application: ndonnellan
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /stylesheets/images
    static_dir: img

  - url: /stylesheets
    static_dir: stylesheets
    
  - url: /scripts
    static_dir: scripts

  - url: /img
    static_dir: img

  - url: /.*
    script: ndonnellan.app
    
libraries:
  - name: jinja2
    version: latest